### PR TITLE
Rubocop - ignore seeds file

### PR DESCRIPTION
**Pull request by taylorkearns**

### CODE REVIEW

**Comment by kevin-j-m** [comment]
Is there a particular style you're concerned about for seeds that's irrelevant? If possible, I'd like to focus on as granular as possible when excluding elements, unless they're generated (schema) or third-party code (vendor).

**Comment by taylorkearns** [comment]
@kevin-j-m yea that's fair, there's really no reason we shouldn't be writing correct ruby in our seeds file. I'm fine w/ closing this.

**Comment by taylorkearns** [comment]
Method length was what I got dinged on.

**Comment by kevin-j-m** [comment]
If there are particular cops you want to turn off for a particular file, please submit a PR with that change. I'm happy to have that discussion.

I'm going to close this.

**Pull request closed without merging**
