### PR TITLE
Exclude keyword args from parameter list count

### PR DESCRIPTION
**Pull request by apalmer0**
```rb
# bad
def foo(param1, param2, param3, param4, param5, param6)
end

# fine
def foo(param1:, param2:, param3:, param4:, param5:, param6:)
end
```
[documentation](https://rubocop.readthedocs.io/en/latest/cops_metrics/#metricsparameterlists)

### CODE REVIEW

**Comment by danfrenette** [comment]
I disagree with this one, if you have a method that takes six args, that's a really complicated method, I don't think that the use of keyword arguments do anything to alleviate that. FWIW I'd also feel the same way if the method took a single argument that was a hash with 6 key/value pairs.

[Gonna end this by punting to the opinion of a developer whose word most people treat as gospel. (Rule 3)](https://thoughtbot.com/blog/sandi-metz-rules-for-developers)

**Comment by kevin-j-m** [comment]
I disagree with this proposed change based on consideration of the most common/greatest good.

In almost all cases, having a method with a large signature, whether it be keyword args or positional args, is likely a design smell that should be considered critically. 

Are there exceptions? Of course. If you were writing a page object with a method to fill in some form, and the form had six fields, then having all six in the signature makes sense - but I'd also have no problem with rubocop nudging you and asking, hey, are you sure that's what you want?

Our adherence to our style guide is based on the general case, and not to ensure there are no exceptions. Our philosophy is to use the guide exactly in that way - as a guide. It's not meant as a command that must be taken, but a suggestion to be considered. To the extent that things make sense some times - great, let's deviate. But having rubocop start the discussion and if nothing else, having the author justify to themselves why this deviation is warranted, can be valuable.

That said, I'm also sympathetic to the case where the feedback from a robot is considered gospel and the author may not have the context to evaluate the contextual difference or benefit from one style over another. I don't have a definitive answer to that, unfortunately, but that's why our approach has been to have the style guide deviation to result as a PR comment, rather than breaking the build or being required to pass as a git pre-commit hook or something. Much like a real-live person may post a suggestion on a PR and the author may not take it, or have a justification for not doing it, the same is the case here, IMO.

I really need to add something like this to the README. I say it too often in some form or another.

**Comment by danfrenette** [comment]
> I really need to add something like this to the README. I say it too often in some form or another.

@kevin-j-m Do you think this fits best in the README or in the Gnar Handbook? I think it's valuable information, but I'm wondering about the ramifications of putting a "Philosophy" section in a public repo when really, I think what your saying is directed solely at Gnar Devs, but I could also be totally misinterpreting that.

**Comment by kevin-j-m** [comment]
I think explaining to the largest audience, or the total audience, who may be using or encountering this, how we use what's in here is valuable. 

And I also think it makes more sense to put it directly with the tool, rather than in some other location entirely. I know personally I'd be less likely to find it if I needed to know to look somewhere else for it.

**Comment by apalmer0** [comment]
Cool! Seems like this is a bad idea, closing. Thanks for the feedback.

**Pull request closed without merging**
